### ISSUE TITLE
转换格式问题

### ISSUE THREAD

**Issue by HX-zhejichensha** [Diaoxiaozhang/Ximalaya-XM-Decrypt#2]
我是用大佬这个工具用来下载喜马拉雅的，xm格式转换后是m4a格式，希望可以增加转换成mp3格式的选项。这样可以方便我放在收音机里面。谢谢大佬

**Comment by Diaoxiaozhang** [comment]
目前阶段建议自己用格式工厂或者ffmpeg转，这个项目只是一个小脚本，不想加太多功能。想要实现这个功能还得加入ffmpeg环境，有点鸡肋。我的另一个项目[Ximalaya-Downloader](https://github.com/Diaoxiaozhang/Ximalaya-Downloader)目前正在制作gui，制作完成后会包含这个项目的功能以及转格式的功能。谢谢支持
