### ISSUE TITLE
id3 != b'ID3'

### ISSUE THREAD

**Issue by 670543400** [Diaoxiaozhang/Ximalaya-XM-Decrypt#21]
解密单个文件
不设置输出路径
raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
mutagen.id3._util.ID3NoHeaderError: '<unknown>' doesn't start with an ID3 tag

**Comment by Diaoxiaozhang** [comment]
请给出xm文件或音频链接

**Comment by 670543400** [comment]
[Uploading c10cebf15438ec82401ba11df0305f17.0&buy_key=b6ea89f918dbe1383242e39584ec7e07&duration=192&sign=6bdc944f624e0769f1ccb63cd1583485&timestamp=1711279728&token=7040&uid=166750171.rar…]()

**Comment by 670543400** [comment]
[Uploading c10cebf15438ec82401ba11df0305f17.0&buy_key=b6ea89f918dbe1383242e39584ec7e07&duration=192&sign=6bdc944f624e0769f1ccb63cd1583485&timestamp=1711279728&token=7040&uid=166750171.rar…]()

**Comment by 670543400** [comment]
[1.gz](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/files/14800499/1.gz)

**Comment by 670543400** [comment]
这是喜马拉雅少儿版 会员下载的一段音频，文件名很长，*.bin。
[Uploading 1.gz…]()

**Comment by 670543400** [comment]
这是喜马拉雅少儿版 会员下载的一段音频，文件名很长，*.bin。
[Uploading 1.gz…]()

**Comment by 670543400** [comment]
这是喜马拉雅少儿版 会员下载的一段音频，文件名很长，*.bin。
[Uploading 1.gz…]()

**Comment by Diaoxiaozhang** [comment]
文件没有成功上传，发一下链接吧
我看你说喜马拉雅少儿版，它下载下来是xm版吗？不确定这个软件是否支持解密

**Comment by Diaoxiaozhang** [comment]
文件没有成功上传，发一下链接吧
我看你说喜马拉雅少儿版，它下载下来是xm格式吗？不确定这个软件是否支持解密

**Comment by 670543400** [comment]
不是xm格式。找到原因了：喜马拉雅分成人版（默认）和儿童版，成人版客户端下载下来是xm格式，儿童版只有手机端，手机端下载下来不是xm格式，是XXXX.bin，所以无法解码。
