### ISSUE TITLE
使用的 python_magic_bin 不支持 Mac M 系列芯片

### ISSUE THREAD

**Issue by RogerHao** [Diaoxiaozhang/Ximalaya-XM-Decrypt#22]
当前使用 Macbook Pro M芯片(M3Max)，安装 Requirements 时，发现 python_magic_bin 无法安装，查看 pipy 官方页面，发现不支持 Mac 的 M 系列芯片，请问是否考虑更换这个依赖包？

**Comment by Diaoxiaozhang** [comment]
mac我不太了解，我查了一下，你可以试试用homebrew安装libmagic然后用python-magic代替python-magic-bin

**Comment by RogerHao** [comment]
感谢，我已经解决这个问题
