### ISSUE TITLE
最新版本好像无法解密XM文件了，解密时一秒内黑框出几行代码直接退出了，希望作者看看怎么回事谢谢啦！

### ISSUE THREAD

**Issue by Speculate9071** [Diaoxiaozhang/Ximalaya-XM-Decrypt#23]

**Comment by Diaoxiaozhang** [comment]
我测试了一下没有发现问题，你可以尝试使用cmd运行本程序看看报错什么信息

**Comment by Diaoxiaozhang** [comment]
你能否在测试一下：1.下载其他音频有没有这个问题2.不设置下载路径有没有这个问题3.旧版本有没有这个问题

**Comment by slayerfrank** [comment]
有的可以，有的就不行了。
Traceback (most recent call last):
  File "C:\Users\FrankFeng\Desktop\Ximalaya-XM-Decrypt-main\main.py", line 221, in <module>
    decrypt_xm_file(file, output_path)
  File "C:\Users\FrankFeng\Desktop\Ximalaya-XM-Decrypt-main\main.py", line 145, in decrypt_xm_file
    output = f"{output_path}/{replace_invalid_chars(info.album)}/{replace_invalid_chars(info.title)}.{find_ext(audio_data[:0xff])}"
  File "C:\Users\FrankFeng\Desktop\Ximalaya-XM-Decrypt-main\main.py", line 138, in find_ext
    raise Exception(f"unexpected format {value}")
Exception: unexpected format audio file with id3 version 2.4.0, contains:mpeg adts, layer iii, v2, 160 kbps, 24 khz, monaural

**Comment by whycao** [comment]
同样有类似问题。请教如何修改？谢谢
正在解密/Music/鹿鼎记/10517125728585acf61fce88b8eadc5f.x3m
Traceback (most recent call last):
  File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 220, in <module>
    decrypt_xm_file(file, output_path)
  File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 146, in decrypt_xm_file
    info, audio_data = xm_decrypt(data)
  File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 85, in xm_decrypt
    xm_info = get_xm_info(raw_data)
  File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 50, in get_xm_info
    id3 = ID3(io.BytesIO(data), v2_version=3)
  File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 76, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 175, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 534, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/_tags.py", line 110, in __init__
    self.load(*args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 151, in load
    self._header = ID3Header(fileobj)
  File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 66, in __init__
    raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
mutagen.id3._util.ID3NoHeaderError: '<u

**Comment by Diaoxiaozhang** [comment]
> 同样有类似问题。请教如何修改？谢谢
> 正在解密/Music/鹿鼎记/10517125728585acf61fce88b8eadc5f.x3m
> Traceback (most recent call last):
>   File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 220, in <module>
>     decrypt_xm_file(file, output_path)
>   File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 146, in decrypt_xm_file
>     info, audio_data = xm_decrypt(data)
>   File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 85, in xm_decrypt
>     xm_info = get_xm_info(raw_data)
>   File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 50, in get_xm_info
>     id3 = ID3(io.BytesIO(data), v2_version=3)
>   File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 76, in __init__
>     super(ID3, self).__init__(*args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 175, in __init__
>     super(ID3Tags, self).__init__(*args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 534, in __init__
>     super(DictProxy, self).__init__(*args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/_tags.py", line 110, in __init__
>     self.load(*args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
>     return func(*args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 156, in wrapper
>     return func(self, h, *args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 151, in load
>     self._header = ID3Header(fileobj)
>   File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
>     return func(*args, **kwargs)
>   File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 66, in __init__
>     raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
> mutagen.id3._util.ID3NoHeaderError: '<unknown>' doesn't start with an ID3 tag

你这不是电脑客户端下载的音频文件吧。。

**Comment by whycao** [comment]
> > 同样有类似问题。请教如何修改？谢谢
> > 正在解密/Music/鹿鼎记/10517125728585acf61fce88b8eadc5f.x3m
> > Traceback (most recent call last):
> > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 220, in 
> > decrypt_xm_file(file, output_path)
> > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 146, in decrypt_xm_file
> > info, audio_data = xm_decrypt(data)
> > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 85, in xm_decrypt
> > xm_info = get_xm_info(raw_data)
> > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 50, in get_xm_info
> > id3 = ID3(io.BytesIO(data), v2_version=3)
> > File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 76, in **init**
> > super(ID3, self).**init**(*args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 175, in **init**
> > super(ID3Tags, self).**init**(*args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 534, in **init**
> > super(DictProxy, self).**init**(*args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/_tags.py", line 110, in **init**
> > self.load(*args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
> > return func(*args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 156, in wrapper
> > return func(self, h, *args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 151, in load
> > self._header = ID3Header(fileobj)
> > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
> > return func(*args, **kwargs)
> > File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 66, in **init**
> > raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
> > mutagen.id3._util.ID3NoHeaderError: '' doesn't start with an ID3 tag↳
> 
> 你这不是电脑客户端下载的音频文件吧。。

安卓手机下载，传到电脑上的的x3m文件，请问可以解X3m文件吗？

**Comment by Diaoxiaozhang** [comment]
> > > 同样有类似问题。请教如何修改？谢谢
> > > 正在解密/Music/鹿鼎记/10517125728585acf61fce88b8eadc5f.x3m
> > > Traceback (most recent call last):
> > > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 220, in 
> > > decrypt_xm_file(file, output_path)
> > > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 146, in decrypt_xm_file
> > > info, audio_data = xm_decrypt(data)
> > > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 85, in xm_decrypt
> > > xm_info = get_xm_info(raw_data)
> > > File "/Desktop/Ximalaya-XM-Decrypt-main/main.py", line 50, in get_xm_info
> > > id3 = ID3(io.BytesIO(data), v2_version=3)
> > > File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 76, in **init**
> > > super(ID3, self).**init**(*args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 175, in **init**
> > > super(ID3Tags, self).**init**(*args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 534, in **init**
> > > super(DictProxy, self).**init**(*args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/_tags.py", line 110, in **init**
> > > self.load(*args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
> > > return func(*args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 156, in wrapper
> > > return func(self, h, *args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/id3/_file.py", line 151, in load
> > > self._header = ID3Header(fileobj)
> > > File "/.local/lib/python3.10/site-packages/mutagen/_util.py", line 185, in wrapper
> > > return func(*args, **kwargs)
> > > File "/.local/lib/python3.10/site-packages/mutagen/id3/_tags.py", line 66, in **init**
> > > raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
> > > mutagen.id3._util.ID3NoHeaderError: '' doesn't start with an ID3 tag↳
> > 
> > 你这不是电脑客户端下载的音频文件吧。。
> 
> 安卓手机下载，传到电脑上的的x3m文件，请问可以解X3m文件吗？

只能解密电脑客户端下载的xm文件
