### ISSUE TITLE
请问作者相关的编译环境是什么，包括Python的版本、依赖包的版本

### ISSUE THREAD

**Issue by zhangliang19950803** [Diaoxiaozhang/Ximalaya-XM-Decrypt#24]
本地用python3.12版本
from wasmer import Store, Module, Instance, Uint8Array, Int32Array, engine
from wasmer_compiler_cranelift import Compiler
这两行依赖始终飘红，不知道该怎么解决，求助

**Comment by Diaoxiaozhang** [comment]
换成3.9试试，包都用最新版的就行
