### ISSUE TITLE
批量解密的时候报错

### ISSUE THREAD

**Issue by youngbais** [Diaoxiaozhang/Ximalaya-XM-Decrypt#29]
批量解密的时候报错，是不是加密的xm文件自身有问题，无法读取到标签？
![QQ截图20240514200205](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/assets/7010890/f464502f-5283-4c86-9a83-47739e98d724)

**Comment by guo-chuanchuan** [comment]
我也遇到了这个问题，是不是无法解密啊

**Comment by AjaxJhu** [comment]
我也遇到了这个问题

**Comment by youngbais** [comment]
> 我也遇到了这个问题，是不是无法解密啊

是下载的xm文件损坏或者不完整.读取不到ID3标签.然后就报错了.重新下载对应的完整xm文件再解密就行了.

**Comment by youngbais** [comment]
> 我也遇到了这个问题

是下载的xm文件损坏或者不完整.读取不到ID3标签.然后就报错了.重新下载对应的完整xm文件再解密就行了.
