### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement python-magic-bin (from versions: none) ERROR: No matching distribution found for python-magic-bin

### ISSUE THREAD

**Issue by chaleaoch** [Diaoxiaozhang/Ximalaya-XM-Decrypt#4]
python版本有需求吗?
我用的python3.10 安装requirements 报错了.

**Comment by Diaoxiaozhang** [comment]
> python版本有需求吗?
> 我用的python3.10 安装requirements 报错了.

你用的什么操作系统？

**Comment by chaleaoch** [comment]
> > python版本有需求吗?
> > 我用的python3.10 安装requirements 报错了.
> 
> 你用的什么操作系统？

没错我用的是linux, 我把requirements 
改成python-magic
就可以工作了.
