### ISSUE TITLE
报错无法解密

### ISSUE THREAD

**Issue by tangli159** [Diaoxiaozhang/Ximalaya-XM-Decrypt#6]
![image](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/assets/50565072/68f29b35-14ae-4285-84fb-b31dc5c6825f)
放了一个单文件进去解密练手，提示如上图。不管是否自定义导出路径，会直接很快显示完上图后退出程序，也没有解密完的文件生成。
专辑ID为5691565，顺手放进去的其中一个文件，所以不知道具体是哪一集。但随机放了两个文件去尝试，结果都一样。

**Comment by Diaoxiaozhang** [comment]
这个项目只能解密喜马拉雅电脑客户端下载的xm后缀文件，x3m应该是手机版下载下来的吧
